version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      NETUID: "52"
      MONGOHOST: "mongodb"
      MONGOPORT: "27017"
      MONGOUSER: "root"
      MONGOPASSWORD: "example"
      SUBTENSOR_NETWORK: "finney"
      ADMIN_API_KEY: "your_admin_api_key_here"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
